<a href="https://colab.research.google.com/github/KodumuruRaja/Regression-Algorithms/blob/main/Multiple-Linear-Regression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df=pd.read_csv("/content/homeprices.csv")

In [ ]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
df['bedrooms']=df['bedrooms'].fillna(df['bedrooms'].median())

In [ ]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
reg=LinearRegression()
reg.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [ ]:
reg.intercept_

array([221323.0018654])

In [ ]:
reg.predict([[3000,3,40]])

array([[498408.25158031]])

In [ ]:
reg.predict([[3500,4,20]])

array([[642462.71080197]])